### ISSUE TITLE
Semantics of daemon/srv.Server.Shutdown() might have race conditions.

### ISSUE THREAD

**Issue by peter-mogensen** [One-com/gone#1]
As a followup to this discussion:
https://groups.google.com/forum/#!topic/golang-nuts/hACrtl4JoUY

The current semantics of Shutdown() on a Server is that it might be dropped if the server is not running. It is not specifically tied to a Serve() invocation.

A read through of the code in daemon/srv/server.go seems to give the conclusion that it's in principle possible for only some of the managed Servers to acknowledge a Shutdown() signal if they have just been started.

It's probably very hard to reproduce - at least reliably ... but it needs to be considered whether the daemon/srv.Server interface needs better semantics.

**Comment by npat-efault** [comment]
If you want to verify whether it can really happen _in principle_, you could greatly relax the timing constraints required for its occurrence. You can do it by adding delays (e.g. time.Sleep() calls) at strategic points. I.e. run the protocol in "slow motion"...

**Comment by peter-mogensen** [comment]
yes... 
The "easy" (not breaking API) solution might just be to declare the Server a single-use object.
Restarting a Server is not really used in the code anyway.
... and then of course change the http.Server implementation to not throw away Shutdown()
The net/http.Server is mostly single-use too unless you work around it. 

On the other hand... rolling a v2 API using Context would probably be an option.

**Comment by peter-mogensen** [comment]
This issue should be fixed by:
* In general removing race-conditions from the reload logic. Especially wrt. signalling.
* Though originally intended for servers to to restartable if the old generation of servers failed to run, this was never used in practice. Servers were always only asked to Serve() once, being single-use.
* FInally... the API for daemon/srv.Server has been deprecated in favor of daemon.Server which relies on context.Context both for Serve() and Shutdown()

...closing this now
